### ISSUE TITLE
Oso package corrupts terminal carriage returns in click prompts

### ISSUE THREAD

**Issue by radiantone** [osohq/oso#1236]
Odd bug here, but I use Oso in my python click CLI app. When using prompts in click, pressing enter key prints a newline (and next prompt on new line), but when oso package is included this gets broken and no linefeed is printed.

`
import click
import oso   # Comment this out to see difference

one = click.prompt('Enter One', type=str, default="one")
two = click.prompt('Enter Two', type=str, default="two")`

**Comment by gj** [comment]
Hi @radiantone! I wasn't able to reproduce this with the following environment:

- zsh 5.8 (x86_64-apple-darwin17.7.0)
- tmux 3.2
- iTerm2 3.4.10
- macOS 10.15.7
- Python 3.9.7

Would you be able to provide similar specs about your environment? It would help us narrow down the issue. Thank you!

**Comment by radiantone** [comment]
Sure. Let me see what my venv has. I'm on Ubuntu 21.04 btw

**Comment by radiantone** [comment]
python 3.9.5
`$ stty -a
speed 38400 baud; rows 35; columns 205; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc`

$ echo $TERM
xterm-256color

**Comment by radiantone** [comment]
Here is the console output
`(venv2) darren@phoenix:~/PycharmProjects/pyfi$ cat test.py 
import click
import oso

one = click.prompt('Enter One', type=str, default="one")
two = click.prompt('Enter Two', type=str, default="two")
(venv2) darren@phoenix:~/PycharmProjects/pyfi$ vi test.py 
(venv2) darren@phoenix:~/PycharmProjects/pyfi$ python test.py 
Enter One [one]: 
Enter Two [two]: 
(venv2) darren@phoenix:~/PycharmProjects/pyfi$ cat test.py 
import click
#import oso

one = click.prompt('Enter One', type=str, default="one")
two = click.prompt('Enter Two', type=str, default="two")
(venv2) darren@phoenix:~/PycharmProjects/pyfi$ 
`

**Comment by gj** [comment]
My coworker tried reproducing this with Python 3.9 on Ubuntu and failed, so unfortunately this seems to be down to some finicky environment-specific issue. Our best guess at the moment is that this conditional import of `readline` is the source of the issue:

https://github.com/osohq/oso/blob/e7e3ba5a9a62805213364441c0202a5dfa14b2ab/languages/python/oso/polar/polar.py#L9-L14

I've created a follow-up task for us to move that conditional import into the `repl()` method in that same file to see if it fixes your issue (so you _might_ still see the same issue if you tried running the REPL or otherwise called that function, but it wouldn't rear its head every time the `polar.py` file is loaded by Python).

At some point before our next release (October 20th), we'll make that change and create a wheel for you to try installing.

Alternatively, if you wanted to, you could test out that fix locally by editing your locally installed `polar.py` file (in the `polar` package; e.g., in my local `venv` the file path to the appropriate file is `venv/lib/python3.9/site-packages/polar/polar.py`).

If you're able to test it out and it fixes your issue, it'd be amazing if you would open a PR with the fix!

**Comment by radiantone** [comment]
Cool. Thanks for looking into guys. Really appreciate that. Will study it more when i return from travel.

**Comment by gj** [comment]
Gonna consider this closed until we hear otherwise 🙂
