### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by gldecurtins** [osohq/oso#1278]
Hi all

I'm trying to install (and follow) the [oso-github-django](https://github.com/osohq/oso-github-django) sample app.
My pip keeps failing to install any version of oso. [django-oso](https://pypi.org/project/django-oso/) got installed, but it fails at [oso](https://pypi.org/project/oso/) itself. Any suggestions?

Version 0.8
```
(venv) gldecurtins@Gians-Mac-mini objektor-django % pip install oso~=0.8  
ERROR: Could not find a version that satisfies the requirement oso~=0.8 (from versions: none)
ERROR: No matching distribution found for oso~=0.8
```

Version 0.21
```
(venv) gldecurtins@Gians-Mac-mini objektor-django % pip install oso==0.21.0
ERROR: Could not find a version that satisfies the requirement oso==0.21.0 (from versions: none)
ERROR: No matching distribution found for oso==0.21.0
```

I'm running Mac OS X 11.6 with Python 3.10.0 (universal2), but also tried Python 3.9.7 (universal2).

**Comment by leina05** [comment]
Hi @gldecurtins,

You're most likely running into this because your Mac mini has an M1 chip. We have an open issue [here](https://github.com/osohq/oso/issues/808) for supporting M1 builds, with some workarounds that you should be able to use to get started.

Please let me know if you still can't get it working. Also you're welcome to join our [slack](https://join-slack.osohq.com/), where you'll probably get a faster response.

**Comment by dhatch** [comment]
Hi @gldecurtins We just added M1 support for Python in Oso 0.22.0, so this should be resolved! I am closing this issue for now but please let us know either here or in [Slack](`http://join-slack.osohq.com`) if you're still having trouble installing Oso.
