### ISSUE TITLE
add release notes (or a link to them) in GitHub releases?

### ISSUE THREAD

**Issue by davepacheco** [osohq/oso#1429]
We're using Dependabot to keep Oso up to date.  If the release notes are in one of a couple of standard places, Dependabot can put them right into the PR that it submits to update the dependency.  [Here](https://github.com/oxidecomputer/omicron/pull/463#issue-1067837523) is what the PRs look like now.  It looks like it grabbed the contents of the GitHub Release's notes, which don't seem all that useful here.  If y'all could put a link to the [blog post](https://www.osohq.com/post/release-oso-0-24-0) there, that'd be a help!

(this is obviously a tiny thing but I figured I'd ask in case it's easy!)

**Comment by saolsen** [comment]
Great idea, how does something like this look https://github.com/osohq/oso/releases/tag/v0.24.0
These are the changelogs we publish in the docs (eg:[ ](https://docs.osohq.com/project/changelogs/2021-12-01.html)

Pretty easy to just copy them here too though since they're already markdown. I'll get this added to our release process.

**Comment by davepacheco** [comment]
That's great!  Thanks.
