### ISSUE TITLE
ForbiddenError include reason

### ISSUE THREAD

**Issue by isimonsm** [osohq/oso#1532]
Hello,

first, thank you for the great library! I am currently migrating our code base and it works great.

Is there a way to pass additional information to the ForbiddenError raised by oso when permission is not granted?
I have an action on a resource that requires three conditions to be met. I would like to give feedback to the client on why their request fails.

At the moment, I only see the option to split each condition into a separate action and catch the ForbiddenError on each oso.authorize call, which feels like missing the point of the library. Instead, I would like to pass a name to each condition (e.g. by specifying each as a rule) and passing it to the ForbiddenError so I can still catch the error globally in my application, but give more feedback to the client by returning the rule name in the response.

Is there an option to do something similar, or a plan to implement an equivalent feature?

Thank you for your help!

**Comment by gw000** [comment]
Hi @isimonsm,

**Comment by gw000** [comment]
Hi @isimonsm ,

This would be a nice feature, but I don't believe we have any current plans to add it. Unfortunately I think splitting up the rule into three separate conditions might be the best option, since the VM doesn't do the kind of tracing it would need to do to give an explanation of exactly how a rule failed internally. Another option, which I wouldn't otherwise recommend, would be to have each of the three conditions call out to an application method to register when they succeed:

```
allow(actor, "action", resource) if cond1(actor, resource) and Trace.ok("cond1") and cond2(actor, resource) and Trace.ok("cond2") and cond3(actor, resource) and Trace.ok("cond3");
```

Then you could have a single `authorize` call, and if it fails you can check the record to see which conditions were met & which weren't. This way you'd be adding the tracing in yourself, basically. The reason I don't recommend this method is that it relies on non-logical features of Polar that might change in the future (namely support for external method calls and sequential evaluation of expressions in rule bodies).

**Comment by isimonsm** [comment]
Hi @gw000,

thank you for the quick answer, that is really unfortunate!
I will go with the first option then for now. I would be glad if you could consider the feature in the future!
