### ISSUE TITLE
Policy fails in Django 3.2.13 (but not in 3.2.12)

### ISSUE THREAD

**Issue by MichaelLampe** [osohq/oso#1561]
[A commit in Django 3.2.13](https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200) introduced a new filter via `self.check_alias`.  This has caused one of our policies to start failing, with an error of `ValueError: Column aliases cannot contain whitespace characters, quotation marks, semicolons, or SQL comments.`.

The value that was being injected by OSO was `'Variable('_component_290')__exists'`

## Policy
```POLAR
# I think I transcribed this correctly
policy_function(string_value, instance: instance) if
  item_ones in instance.item_ones and
  item_two in item_ones.item_two and
  item_two.string_value == string_value;
```

Where `item_ones` is a reverse reference on  `instance` and `item_two` is a FK attached to that set's item types.

Will try to create a better reproduction, but couldn't find anything (Because the Django release was just made), so figured I'd surface it.

## Larger Stack Trace
```PYTHON
  python3.8/site-packages/django_oso/models.py", line 28, in authorize
    filter = authorize_model(
  python3.8/site-packages/django_oso/auth.py", line 100, in authorize_model
    next_filter = partial_to_query_filter(resource_partial, model)
  python3.8/site-packages/django_oso/partial.py", line 277, in partial_to_query_filter
    return fb.finish()
  python3.8/site-packages/django_oso/partial.py", line 246, in finish
    filtered = subq.model.objects.filter(subq.finish()).values("pk")
  python3.8/site-packages/django_oso/partial.py", line 250, in finish
    objects = objects.annotate(**{name: exists}).filter(**{name: True})
  python3.8/site-packages/django/db/models/query.py", line 1091, in annotate
    return self._annotate(args, kwargs, select=True)
  python3.8/site-packages/django/db/models/query.py", line 1130, in _annotate
    clone.query.add_annotation(
  python3.8/site-packages/django/db/models/sql/query.py", line 1062, in add_annotation
```

## Context
django-oso = "0.25.1"
django = "3.2.13"

**Comment by samscott89** [comment]
Hey @MichaelLampe. Thanks for opening an issue!

In this case, it looks like this might be a bug on our side that already existed, but that Django 3.2.13 is helpfully raising.

Thanks for supplying the stack trace! That's indicating that the problem comes from this subquery we construct: https://github.com/osohq/oso/blob/main/languages/python/django-oso/django_oso/partial.py#L247-L250

It looks like we're constructing the filter builder name based on the [string representation](https://github.com/osohq/oso/blob/cdbe1e2fc7521a07ecfa079a3a731164a0b2c0ff/languages/python/oso/polar/variable.py#L4-L5) of the variable `Variable(var_name)` rather than the actual variable name. I think this is the offending code: https://github.com/osohq/oso/blob/main/languages/python/django-oso/django_oso/partial.py#L207

Changing `name=left` to `name=str(left)` should fix that. Would you be able to test locally whether that addresses your issue and let us know?

**Comment by MichaelLampe** [comment]
# Reproduction Examples

## Example Policy
```
allow(code, _, parent_object: product::ParentObject) if
  child in parent_object.children and
  value in child.value and
  value.code == code;
```

## Example Models
```
class ParentObject(GenericModel):
    pass

class CodeValue(GenericModel):
    code = models.CharField(max_length=255)

class ChildObject(GenericModel):
    parent = models.ForeignKey(ParentObject, on_delete=models.CASCADE, related_name="children")
    value = models.ForeignKey(CodeValue, on_delete=models.CASCADE)
```

## Example Test
```
class QuickTest(TestFixture):
    def test_quick(self):
        # Just needs to run to pass
        result = ParentObject.objects.authorize(None, actor="1234", action="test").all()
```


## Fixes in progress
Change `name=left` to `name=str(left)`

### New error
```
File "/python3.8/site-packages/django_oso/models.py", line 28, in authorize
    filter = authorize_model(
  File "/python3.8/site-packages/django_oso/auth.py", line 100, in authorize_model
    next_filter = partial_to_query_filter(resource_partial, model)
  File "/python3.8/site-packages/django_oso/partial.py", line 276, in partial_to_query_filter
    fb.translate_expr(partial)
  File "/python3.8/site-packages/django_oso/partial.py", line 132, in translate_expr
    self.and_expr(expr)
  File "/python3.8/site-packages/django_oso/partial.py", line 146, in and_expr
    self.translate_expr(arg)
  File "/python3.8/site-packages/django_oso/partial.py", line 136, in translate_expr
    self.in_expr(expr)
  File "/python3.8/site-packages/django_oso/partial.py", line 205, in in_expr
    model = get_model_by_path(base_query.model, subquery_path)
  File "/python3.8/site-packages/django_oso/partial.py", line 54, in get_model_by_path
    model = model._meta.get_field(attr).related_model
  File "/python3.8/site-packages/django/db/models/options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: ParentObject has no field named 'value'
```

This seems to be caused by the fact that, with the change `base_query = root.get_query_from_var(right_path[0]) or root` now is populated (`{Variable('_child_115'): <django_oso.partial.FilterBuilder object at 0x7fbac1a08400>}` vs `BASE QUERY VARIABLES: {}`).  Unsure if this has actually fixed the initial issue, as the code progresses less far.

Still trying to get up-to-speed on what the code is doing exactly, but this is a good checkpoint to communicate back to y'all.

**Comment by samscott89** [comment]
Hey @MichaelLampe or @MurphyMarkW! Would one of you be able to test the code in #1568 to see if it works for your use case? I was able to reproduce the bug on django 3.2.13 locally with out test suite. We can't yet upgrade the tests to run on 3.2 since it changed the SQL formatting a bunch, and we check those for consistency.

**Comment by MurphyMarkW** [comment]
This appears to pass our tests w/ django 3.2.12 and 3.2.13. Thanks for the assist!
